#!/usr/bin/env sh
echo "Executando testes E2E antes do push..."
cd e2e && npm test
if [ $? -ne 0 ]; then
  echo "Testes E2E falharam. Push bloqueado."
  exit 1
fi
echo "Todos os testes passaram. Push liberado."
